### ISSUE TITLE
Hello, after compressing the node, there is a missing loading progress bar. Nodes with the rgthree switch and setnode cannot be compressed properly

### ISSUE THREAD

**Issue by sky958958** [RiceRound/ComfyUI_CryptoCat#3]
Hello, after compressing the node, there is a missing loading progress bar. Nodes with the rgthree switch and setnode cannot be compressed properly

**Comment by RiceRound** [comment]
The issue with the missing loading progress bar is indeed present. While these nodes still report progress during internal operations, the page's progress calculator uses the total number of nodes divided by the number of completed nodes.

As for the rgthree switch, I don't think it's suitable to place it inside the encryption node. You could place CryptoCat either before or after the switch.
